### ISSUE TITLE
Upstreaming this?

### ISSUE THREAD

**Issue by Waqar144** [Larpon/kate-syntax-highlight-v#1]
Can you consider upstreaming this so that it is automatically available?

**Comment by larpon** [comment]
Yes. I have talked to the maintainers about it some time ago and, IIRC, they expect submitters to be able to maintain the highlighting files to a certain degree - I agree with them, but can not promise that I'd go and check their bug trackers for entries etc. I just don't have the time - I'd be happy to  help and fix bugs here - but it'll take someone else to keep the KDE upstream folks happy. I think it's also easier to maybe wait until V reaches v1.0.

If anyone reads this; know that you're more than welcome to send this repository to upstream KDE/kate - I just don't have the time or resources to maintain it currently.

**Comment by Waqar144** [comment]
Probably you misunderstood the expectation part. Its right that we expect submitters to maintain stuff, of course, but its not a requirement as its FOSS/volunteer stuff in the end. 

I hope you agree that not having the syntax file at all is worse than having one which works to some extent. I can understand your position to some extent as V was changing a lot back in the early days, maybe its not true anymore?

I can submit this upstream if you like, but can this be licensed under MIT? (KSyntaxHighlighting is MIT). I can even forward patches from you provided you tag me/ let me know of any changes you would like to upstream.
(I am one of the devs behind KText* stuff.)

**Comment by larpon** [comment]
> Probably you misunderstood the expectation part. Its right that we expect submitters to maintain stuff, of course, but its not a requirement as its FOSS/volunteer stuff in the end.

I can't remember the details - I've tried searching bugs.kde.org and invent.kde.org for my communication with you guys - but it came out with only entries in krita which I've been active with some years back.

> I hope you agree that not having the syntax file at all is worse than having one which works to some extent. I can understand your position to some extent as V was changing a lot back in the early days, maybe its not true anymore?

Fully agree, V is also changing less and less syntax-wise these days - so I'd be happy if this can be upstreamed.

> I can submit this upstream if you like, but can this be licensed under MIT? (KSyntaxHighlighting is MIT). I can even forward patches from you provided you tag me/ let me know of any changes you would like to upstream. (I am one of the devs behind KText* stuff.)

That would be very kind of you. The license is copied from some random existent highlight file - again it's so long ago that I don't remember what file (probably one from my Kubuntu distribution). Can you provide me with a text template for the MIT license you use - I'll update it ASAP

**Comment by Waqar144** [comment]
You can just mention the license like this:

https://github.com/KDE/syntax-highlighting/blob/73f6da7e754b864a0ea8831d035f27cea6bfa879/data/syntax/zig.xml#L3

**Comment by larpon** [comment]
Done in 8e5d18a

I have access to https://invent.kde.org BTW so we can take communications there if that's easier for you?

**Comment by Waqar144** [comment]
Sure. MR here https://invent.kde.org/frameworks/syntax-highlighting/-/merge_requests/425
